---
- name: Upgrade distro (apt-get full-upgrade)
  apt:
    upgrade: full
    autoremove: yes
    autoclean: yes

- name: Install package pre-reqs
  apt:
    package: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release